-- liquibase formatted sql

-- changeset zohaibahmedbutt:1745095956091-1
-- preconditions onFail:MARK_RAN onError:MARK_RAN
CREATE TABLE IF NOT EXISTS "authors" ("id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, "age" INTEGER, "name" VARCHAR(255), CONSTRAINT "authors_pkey" PRIMARY KEY ("id"));
-- rollback drop table articles cascade;

-- changeset zohaibahmedbutt:1745095956091-2
-- preconditions onFail:MARK_RAN onError:MARK_RAN
CREATE TABLE IF NOT EXISTS "books" ("isbn" VARCHAR(255) NOT NULL, "title" VARCHAR(255), "author_id" BIGINT, CONSTRAINT "books_pkey" PRIMARY KEY ("isbn"));
ALTER TABLE "books" ADD CONSTRAINT "fkfjixh2vym2cvfj3ufxj91jem7" FOREIGN KEY ("author_id") REFERENCES "authors" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;
-- rollback drop table books;

-- changeset zohaibahmedbutt:1745095956091-3
-- preconditions onFail:MARK_RAN onError:MARK_RAN
INSERT INTO "authors" ("age", "name") VALUES (30, 'John Doe');
-- rollback truncate table authors cascade;
